### ISSUE TITLE
Connect account events failing with No such event

### ISSUE THREAD

**Issue by amratab** [integrallis/stripe_event#93]
I am trying to receive account.updated event for my connected accounts to check for verification details. But, it keeps failing with 
```
(Status 404) (Request req_QGxSOsgE2KL) No such event: evt_1BFIYMH49LEORsw2HgV9
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stripe_event-1.8.0/lib/stripe_event.rb:25:in `rescue in instrument'
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stripe_event-1.8.0/lib/stripe_event.rb:16:in `instrument'
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stripe_event-1.8.0/app/controllers/stripe_event/webhook_controller.rb:12:in `event'
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:188:in `process_action'
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /Users/abc/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
```
Since this is an event for connected account, its not present in my event logs so its being rejected by the gem. Is there a configuration to stop this check?

**Comment by amratab** [comment]
Got a solution for it.

**Comment by amratab** [comment]
Still need a solution

**Comment by amratab** [comment]
Resolved

**Comment by mooreds** [comment]
@amratab how did you resolve this?  I'm running into the same issue and would love to know.

**Comment by rmm5t** [comment]
@mooreds What version of stripe_event are you running? With the latest version, this specific kind of error shouldn't be possible anymore.

**Comment by mooreds** [comment]
@rmm5t you are absolutely correct.  I was using 1.5.1, but upgrading to 2.0.0 helped with this issue.
